name: coala
favicon: null
layout_spectrum: 0.95444
typography_spectrum: 0.61332
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#daedf1'
    - '#403823'
    - '#62655a'
    - '#8fa8ac'
  brandStrength: 0.75
  lightness: 0.375
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
